version: "3"

services:
  app:
    container_name: app
    build: .
    ports:
      - "8000:8000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./app/:/app/
    command: sh -c "uvicorn server:app --host 0.0.0.0 --port 8000 --reload"
